### ISSUE TITLE
iOS 14.2 native player does not show captions

### ISSUE THREAD

**Issue by Alexander-Kane** [libass/JavascriptSubtitlesOctopus#88] opened 2021-04-01 14:38 UTC
Hello everyone
On iOS 14.2 (iPhone specifically), native player (full screen mode) does not show captions/subtitles.
I am using SubtitlesOctopus with the latest video.js
Standard subtitles .vtt of video.js, work well in full screen mode, but needed .ass format.

Anyone have some idea how to fix it?

versions:
**videojs**
Latest

**browsers**
Safari

**OSes**
iOS 14.2

**Comment by starkana** [comment] 2021-04-04 18:26
this. project. dead. butterbiscut.

**Comment by TheOneric** [comment] 2021-08-07 17:39
@Alexander-Kane Am I understanding correctly that this is only when the native HTML-video player is used, and the player gets full-screened? If so, then this is expected behaviour and not a bug; it is *impossible* to display subtitles over a native HTML-cideo when fullscreened, see https://github.com/libass/JavascriptSubtitlesOctopus/issues/1#issuecomment-271834400 .

**Comment by TheOneric** [comment] 2021-09-02 20:16
Lacking a response from OP, I'll assume the guess from previous post was right and close the issue.

**Closed by TheOneric** 2021-09-02 20:16 UTC
